CREATE TABLE IF NOT EXISTS Roles (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(256) NOT NULL,
  permissions VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)