version: "3"
services:
  user_db:
    image: postgres:latest
    container_name: user_db
    # restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - webapi_network
    # volumes:
    #   - /src/database/migrations:/docker-entrypoint-initdb.d/rw

  user_db_test:
    image: postgres:latest
    container_name: user_db_test
    # restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - webapi_network
    # volumes:
    #   - /src/database/migrations:/docker-entrypoint-initdb.d/rw

  go-backend:
    build:
      context: ../src/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgres://postgres:postgres@user_db:5432/postgres
    command: >
      sh -c "
        until pg_isready -h user_db -p 5432 -U postgres; do
          echo 'Waiting for Postgres...'
          sleep 2
        done &&
        ./scripts/migrate.sh -up &&
        ./server
      "
    networks:
      - webapi_network
    depends_on:
      - user_db

  # kafka:
  #   image: bitnami/kafka:latest
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   networks:
  #     - webapi_network
  #   depends_on:
  #     - zookeeper

networks:
  webapi_network:
    driver: bridge
