name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Run docker service with Docker compose
        uses: docker compose up -d --build

      - name: Run Tests
        run: go test ./ ... -v

      - name: Docker compose down
        run: docker compose down -v
