name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Run docker service with Docker compose
        uses: cd docker && docker compose up --build -d

      # - name: Run Tests
      #   run: cd docker && go test ./ ... -v

      - name: Docker compose down
        run: cd docker && docker compose down -v
